### ISSUE TITLE
Default charset

### ISSUE THREAD

**Issue by stojankoncar** [Crim/pardot-java-client#35]
HttpClientRestClient.java
```
private <T> T submitRequest(final String url, Map<String, String> postParams, final ResponseHandler<T> responseHandler) throws IOException {
...
            post.setEntity(new UrlEncodedFormEntity(params));
...
}

```
By default new UrlEncodedFormEntity(params) uses HTTP.DEF_CONTENT_CHARSET (ISO_8859_1)

With that a lot of languages are going to struggle - maybe UTF-8 will be a better fit?

`            post.setEntity(new UrlEncodedFormEntity(params, Consts.UTF_8));
`

Or at least method/config should be exposed.

`            post.setEntity(new UrlEncodedFormEntity(params, configuration.getDefContentCharset()));
`

**Comment by Crim** [comment]
Thanks for submitting this as a bug!  I've pushed a fix into master and will publish a new release version soon.
