### ISSUE TITLE
print too many logs

### ISSUE THREAD

**Issue by tfranchiDD** [Crim/pardot-java-client#44]
is it possible to inhibit the logs printing that this pardot library? When you get the template it is printed on the console filling the available space.

**Comment by Crim** [comment]
So the library makes use of the [slf4j](http://www.slf4j.org/manual.html) logging facade.  Which ever logging library you use (log4j, logback, etc..) you should be able to configure the log level for the `com.darksci.pardot.api` namespace.

**Comment by tfranchiDD** [comment]
Hi, could I please get an example of this configuration? I've faced some issues.

**Comment by Crim** [comment]
Which logging library do you use?

[Heres an example](https://github.com/SourceLabOrg/kafka-webview/blob/master/kafka-webview-ui/src/test/resources/logback.xml) (from another project) which uses logback.  It specifies on line 4 to log anything at `org.springframework.web` INFO level and higher.  Then below it specifies several others to only log WARN level and above.

Alternatively if you use log4j2 [here](https://logging.apache.org/log4j/2.x/manual/configuration.html#XML) is a link to their configuration documentation.

**Comment by tfranchiDD** [comment]
Ok, thanks
