### ISSUE TITLE
Email Test List

### ISSUE THREAD

**Issue by tfranchiDD** [Crim/pardot-java-client#48]
Hi, when we try to create a list on the Pardot training environment we don't have the possibility to create a test list. In this kind of environments only test email lists can be sent.

In the List class we have only these properties:

private Long id;

private String name;

private String title;

private String description;

private Boolean isPublic;

private Boolean isDynamic;

private Boolean isCrmVisible;

@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
private LocalDateTime createdAt;

@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
private LocalDateTime updatedAt;

**Comment by Crim** [comment]
It looks like Pardot's API doesn't support making a list a test list?

[Pardot API List Object](http://developer.pardot.com/kb/object-field-references/#list)

**Comment by Crim** [comment]
Yea, no support over the API for creating test lists.  I think you'd need to submit a feature request to the Pardot team :/
