### ISSUE TITLE
Email Template Sender

### ISSUE THREAD

**Issue by tfranchi** [Crim/pardot-java-client#54]
Hi, 

we use this library to send emails thought Pardot. When constructing the EmailSendOneToOneRequest request and we don't  fill the withFromUserId field we get this error:

One or more required parameters are missing: (from_name AND from_email) OR from_user_id

Why isn't used the sender defined in the template?

**Comment by Crim** [comment]
Hi!

I may be misunderstanding, but based on [Pardot's API Email Sending Docs](http://developer.pardot.com/kb/api-version-3/emails/#sending-one-to-one-emails) - When sending an Email over the API you need to do one of the following:

## A - Supply the from_name AND from_email parameters
```
.withFromName("Some Name")
.withFromEmail("Some@email.com")
```

**OR**

## B - Supply the from_user_id parameter
```java
.withFromUserId(123L)
```


Are you able to share how you are setting up the request and which parameters you are setting?
