### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by tfranchi** [Crim/pardot-java-client#56]
Hi, 

is there any way to use pardot's dynamic content via API?

I can't find a way to download this content.

**Comment by Crim** [comment]
Ah yea, it looks like those end points haven't been implemented in this library yet.  

From reviewing the [Pardot API Docs](http://developer.pardot.com/kb/api-version-3/dynamic-content/) for DynamicContent, it supports querying and reading dynamic content, but not creating or editing dynamic content.

**Comment by tfranchi** [comment]
yes, we need only retrieve dynamic content from Pardot. Will this feature be implemented shortly?

**Comment by Crim** [comment]
This should be included in the 2.1.0 release I just published.
