### ISSUE TITLE
ProspectQueryRequest: could you add a withUpdateAfter?

### ISSUE THREAD

**Issue by lzpup** [Crim/pardot-java-client#65]
Something like: 
/**
     * Selects prospects that were last updated after the specified time
     * @param updateAfter The date to filter.
     * @return RequestBuilder
     */
    public ProspectQueryRequest withUpdateAfter(DateParameter updateAfter) {
        return setParam("updated_after", updateAfter);
    }

Thank you for the package. Thank you for updating with the new Authentication

**Comment by Crim** [comment]
Hey thanks for letting me know that was missing!  I've updated the code and released 3.1.0 which should include support for it.

Let me know if you run into any troubles with this, or anything else, happy to help!
Thanks!
