### ISSUE TITLE
Web Server OAuth flow implementation

### ISSUE THREAD

**Issue by epic-alex-rodionov** [Crim/pardot-java-client#68]
Salesforce provides many different OAuth flows to meet specific security and integration needs. Currently only password flow is implemented. So it would be good to have Web Server OAuth flow implementation, which works with grant_type=authorization_code and access token.

This flow is great when you want the end-user to enter their credentials to authorize the integration and you don’t want to store the credentials on your system since it could be a security risk.

**Comment by Crim** [comment]
What do you think is the best way to implement this?  Do you think we should open up the [SessionRefreshHandler](https://github.com/Crim/pardot-java-client/blob/8f456a766cec9513aa42bc31c48abd84e732446f/src/main/java/com/darksci/pardot/api/auth/SessionRefreshHandler.java#L23) interface so developers can pass their own implementation?

Or do you think we should write our own implementation of the Web Server OAuth flow?  Or perhaps both?

Thoughts? 
Thanks!

**Comment by epic-alex-rodionov** [comment]
Well, it would be good to have more flexible client to be able to use different auth variants. Yes, maybe both is better, but SessionRefreshHandler maybe has more priority. Thanks!

**Comment by Crim** [comment]
I put together an extremely rough idea of how this could work.  I need to verify we can implement alternative authentication flows using the [PardotClient::userDefinedRequest()](https://github.com/Crim/pardot-java-client/blob/8836246b0eb974dff41ae5f4a1a9239cb43947c0/src/main/java/com/darksci/pardot/api/PardotClient.java#L1119) method from the updated [SessionRefreshHandler::refreshCredentials](https://github.com/Crim/pardot-java-client/blob/8836246b0eb974dff41ae5f4a1a9239cb43947c0/src/main/java/com/darksci/pardot/api/auth/SessionRefreshHandler.java#L45) interface method.

I'll continue to play around with this soon.

**Comment by epic-alex-rodionov** [comment]
Thank you @Crim.

**Comment by Crim** [comment]
I released version `3.2.0` which the following methods on `ConfigurationBuilder` to allow for using a RefreshToken or AccessToken for authenication.

If you use the AccessToken method, it has no way to automatically refresh/renew the session when it expires.  If you use the RefreshToken method, it will automatically refresh/renew the session if it expires.


```java
/**
     * For configuring authenticating to the Pardot API using the password OAuth2 authentication flow.
     *
     * @param username Salesforce username.
     * @param password Salesforce user's password.
     * @param clientId Connected Application client or consumer Id.
     * @param clientSecret Connected Application client or consumer secret.
     * @param businessUnitId Id of the Pardot business unit to connect to.
     * @return Builder instance.
     */
    public ConfigurationBuilder withSsoLogin(final String username, final String password, final String clientId, final String clientSecret, final String businessUnitId) 
```

and

```java
/**
     * For configuring authenticating to the Pardot API using a refresh_token acquired using
     * the access_code oauth2 authentication flow.
     *
     * @param refreshToken Salesforce refresh_token.
     * @param clientId Connected Application client or consumer Id.
     * @param clientSecret Connected Application client or consumer secret.
     * @param businessUnitId Id of the Pardot business unit to connect to.
     * @return Builder instance.
     */
    public ConfigurationBuilder withSsoRefreshTokenLogin(final String refreshToken, final String clientId, final String clientSecret, final String businessUnitId)
```

Alternatively I've also exposed the following method and `SessionRefreshHandler` interface that allows you to define
your own session handler.  I think ideally out of the box this library would/should support the most common scenarios however.

```java
/**
     * Allows for injecting a custom {@link SessionRefreshHandler} implementation.
     * @param sessionRefreshHandler Interface for handling authentication to Pardot API.
     * @return Builder instance.
     */
    public ConfigurationBuilder withCustomAuthenticationHandler(final SessionRefreshHandler sessionRefreshHandler) 
```

Let me know if this solves your use case, or if there's still something outstanding that you're unable to do.

Thanks!

**Comment by epic-alex-rodionov** [comment]
@Crim thank you very much! I will try integrate it soon and will put a comment after!

**Comment by epic-alex-rodionov** [comment]
@Crim I use `withSsoRefreshTokenLogin` method and it looks working, not issues so far! Thank you for very fast fixing this issue!

**Comment by Crim** [comment]
Awesome! Glad to hear it!
