### ISSUE TITLE
Test Environment invalid grant

### ISSUE THREAD

**Issue by tfranchi** [Crim/pardot-java-client#70]
In class SsoLoginRequest there is getApiHostname stub method that return always https://login.salesforce.com.

For the test environment, the login failed.

**Comment by Crim** [comment]
Ah so you'd want to login against say a sandbox org?  That makes sense, I think we should be able to configure which hostname it tries to auth against ya?

**Comment by Crim** [comment]
I released version `3.2.0` which adds the following methods on `ConfigurationBuilder` to allow for Overriding the OAuth Authorization server.

```java
/**
     * For configuring authenticating to the Pardot API using the password OAuth2 authentication flow.
     *
     * @param username Salesforce username.
     * @param password Salesforce user's password.
     * @param clientId Connected Application client or consumer Id.
     * @param clientSecret Connected Application client or consumer secret.
     * @param businessUnitId Id of the Pardot business unit to connect to.
     * @param authorizationServer Override the authorization server address.
     * @return Builder instance.
     */
    public ConfigurationBuilder withSsoLogin(final String username, final String password, final String clientId, final String clientSecret, final String businessUnitId, final AuthorizationServer authorizationServer) 
```

and

```java
/**
     * For configuring authenticating to the Pardot API using a refresh_token acquired using
     * the access_code oauth2 authentication flow.
     *
     * @param refreshToken Salesforce refresh_token.
     * @param clientId Connected Application client or consumer Id.
     * @param clientSecret Connected Application client or consumer secret.
     * @param businessUnitId Id of the Pardot business unit to connect to.
     * @param authorizationServer Override the authorization server address.
     * @return Builder instance.
     */
    public ConfigurationBuilder withSsoRefreshTokenLogin(final String refreshToken, final String clientId, final String clientSecret, final String businessUnitId, final AuthorizationServer authorizationServer)
```

You can pass `AuthorizationServer.DEFAULT_SALESFORCE`, `AuthorizationServer.SANDBOX_SALESFORCE`  which are defined as:

```java
    /**
     * The default Authorization Server for production salesforce.
     */
    public static final AuthorizationServer DEFAULT_SALESFORCE = new AuthorizationServer(
        "https://login.salesforce.com",
        "/services/oauth2/token"
    );

   /**
     * The default Authorization Server for test/sandbox instances.
     */
    public static final AuthorizationServer SANDBOX_SALESFORCE = new AuthorizationServer(
        "https://test.salesforce.com",
        "/services/oauth2/token"
    );
```


Or alternatively you can construct your own `AuthorizationServer` instance with whatever values you need.

Let me know if this solves the problem you were having.

Thanks!

**Comment by tfranchi** [comment]
Thanks!

**Comment by tfranchi** [comment]
Hi,

now I get an access denied response from pardot when I use AuthorizationServer.SANDBOX_SALESFORCE.

I think that the request URL to pardot is incorrect: for test-environment should be https://pi.demo.pardot.com instead of https://pi.pardot.com

**Comment by Crim** [comment]
Ah, so its a bit confusing.   The above only lets you change which Salesforce org you authorize against (a "production" one or a test/"sandbox").

If your Pardot account is on pi.demo.pardot.com, and the Salesforce Org that is connected to your Pardot account is NOT a sandbox org, you only need to do call the [withDemoApiHost()](https://github.com/Crim/pardot-java-client/blob/master/src/main/java/com/darksci/pardot/api/ConfigurationBuilder.java#L251-L258) method on ConfigurationBuilder.

If your Pardot account is on pi.demo.pardot.com. and the Salesforce Org that is connected to your Pardot account IS a sandbox org,  you'll need to call `withDemoApiHost()` as well as override the authorization server to AuthorizationServer.SANDBOX_SALESFORCE
