### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by NathanClassen** [Crim/pardot-java-client#73]
Is there any documentation for the library? The links just take one to the Pardot API...
Having to rely on suggestion for my IDE to figure out how this thing works.

**Comment by Crim** [comment]
Sorry, docs are limited to the [README.md](https://github.com/Crim/pardot-java-client/blob/master/README.md) and limited exampled can be found in the [integration test cases](https://github.com/Crim/pardot-java-client/blob/0dbf134a4ae091ad2c6c2f6aadeb8c7be515e0dd/src/test/java/com/darksci/pardot/api/AbstractPardotClientIntegrationTest.java#L139).

Definitely welcome contributions if you're interested in writing docs :)
