### ISSUE TITLE
deleted Search Criteria Not implemented

### ISSUE THREAD

**Issue by krutishilp** [Crim/pardot-java-client#74]
I am using this library . I have requirement to get Prospects which are deleted but deleted search criteria not implemented yet.
Thanks in advance.

**Comment by Crim** [comment]
Are you using the `ProspectQueryRequest` object to construct your search criteria?  

You can use the `withArchivedOnly()` methods to filter based on if a prospect is archived or not.  [See code](https://github.com/Crim/pardot-java-client/blob/master/src/main/java/com/darksci/pardot/api/request/prospect/ProspectQueryRequest.java#L113-L137).

**Comment by krutishilp** [comment]
Yes, Got It . Thank you.
