### ISSUE TITLE
Send List Email

### ISSUE THREAD

**Issue by tfranchi** [Crim/pardot-java-client#77]
Hi,

we have encountered an issue in send list email, below our code:

```
ListCreateRequest requestList = new ListCreateRequest ();
com.darksci.pardot.api.response.list.List list = new com.darksci.pardot.api.response.list.List ();
list.setCrmVisible(false);
list.setDynamic(true);
list.setPublic(false);
list.setName("Remedy Email List - " + UUID.randomUUID().toString().substring(0, 8));
list.setTitle(list.getName());
requestList.withList(list);
list = pardot.listCreate(requestList);

for (Long prospectId : listIds) {
  ListMembership listMembership = new ListMembership ();
  listMembership.setProspectId(prospectId);
  listMembership.setListId(list.getId());
  listMembership.setOptedOut(false);
  ListMembershipCreateRequest members = new ListMembershipCreateRequest ();
  members.withListMembership(listMembership);
  pardot.listMembershipCreate(members);
}

EmailSendListRequest request = new EmailSendListRequest ();
request.withCampaignId(this.getCampaignId());
request.withListIds(Arrays.asList(new Long [] {list.getId()}));
request.withFromUserId(pardotUser.getId());
request.withName(pardotUser.getFirstName());
request.withHtmlContent(htmlText);
request.withTextContent(text);
request.withSubject(StringUtils.isEmpty(requestDto.getSubject()) ? emailTemplate.getSubject() : requestDto.getSubject());
request.withEmailTemplateId(emailTemplate.getId());
DateTime dateTime = new DateTime ();
dateTime = dateTime.withFieldAdded(DurationFieldType.minutes(), 1);
request.withScheduledTime(dateTime);

Email email = email = pardot.emailSendList(request);
```

when we call `pardot.emailSendList(request);` the library doesn't return and the thread remaining blocked inside this method. 
This issue occurs only for some prospect, so could depend from pardot APIs?

we are using 3.2.0 version of your library.

**Comment by Crim** [comment]
Hmm.  Do you see the request being sent out over to Pardot in the logs?

**Comment by tfranchi** [comment]
No, how we can enable library logs?

**Comment by Crim** [comment]
This library uses [slf4j](https://github.com/Crim/pardot-java-client/blob/master/pom.xml#L105-L109) as a generic logging api for publishing log messages.  You'd need to include and/or configure your own logging framework (logback, log4j,log4j2, etc..) to receive the log messages in your project.

Alternatively you could set a break point in your code in [PardotClient line 265](https://github.com/Crim/pardot-java-client/blob/master/src/main/java/com/darksci/pardot/api/PardotClient.java#L265) and step thru the code from there and see where it hangs.

I'm curious if it's a bug in this client library somewhere that's causing it to hang, or if the request gets sent out to Pardot's servers, and Pardot just hangs processing the request and returning a response.  Unfortunately it's hard to say without more information via log messages, or stepping through it with a debugger :/

**Comment by tfranchi** [comment]
Not a bug. We found an error before while creating a list membership:

"ListMembership add is in exception: That prospect is already a member of that list. Update the membership instead."

Thanks.
