### ISSUE TITLE
Prospect not linked to Crm Contact

### ISSUE THREAD

**Issue by tfranchi** [Crim/pardot-java-client#80]
Hi, we are using this library to integrate our app with pardot.

Our prospect request:
`
ProspectCreateRequest prospectCreate = new ProspectCreateRequest ();
Prospect prospect = new Prospect ();
prospect.setEmail(contactSf.getEmail());
prospect.setPhone(contactSf.getMobilePhone());
prospect.setFirstName(contactSf.getFirstName());
prospect.setLastName(contactSf.getLastName());
prospect.setCampaignId(this.getCampaignId());
prospect.setDoNotEmail(false);
prospect.setOptedOut(false);
prospect.setCrmContactFid(contactSf.getSfid());
prospect.setCustomField("Language", contactSf.getPreferredLanguage());
prospectCreate.withProspect(prospect);
resultProspect = Optional.of(pardot.prospectCreate(prospectCreate));
`

but on pardot this prospect isn't linked to relative contact on salesforce, and when we print the resulting prospect the field crmContactFid is null:

`log.info("Prospect added: {0}", resultProspect.get().toString());`

Prospect added: Prospect{id=55127585, campaignId=182472, salutation='null', firstName='null', lastName='Test', email='test-1234@yopmail.com', company='null', prospectAccountId=0, website='null', jobTitle='null', department='null', country='null', addressOne='null', addressTwo='null', city='null', state='null', territory='null', zip='null', phone='null', fax='null', source='null', annualRevenue='null', employees='null', industry='null', yearsInBusiness='null', comments='null', notes='null', score=0, grade='null', lastActivityAt=null, recentInteraction='Never active.', salesforceFid='null', crmLeadFid='null', **crmContactFid**='null', crmOwnerFid='null', crmAccountFid='null', crmLastSync=null, crmUrl='null', isDoNotEmail=false, isDoNotCall=false, optedOut=false, isReviewed=false, isStarred=false, createdAt=2021-06-25T09:28:36.000, updatedAt=2021-06-25T09:28:36.000, assignedTo=null, customFields={}, campaign=Campaign{id=182472, name='Transactional Notifications', cost=null, folderId=null}, profile=Profile{id=723, name='Default', profileCriteria=[ProfileCriteria{id=3627, name='Company Size', matches='Unknown'}, ProfileCriteria{id=3629, name='Industry', matches='Unknown'}, ProfileCriteria{id=3631, name='Location', matches='Unknown'}, ProfileCriteria{id=3633, name='Job Title', matches='Unknown'}, ProfileCriteria{id=3635, name='Department', matches='Unknown'}]}, visitorActivities=null, listSubscriptions=null, visitors=null}

Why when we create a prospect with contact sf id this isn't created linked to the Salesforce Contact?

**Comment by Crim** [comment]
Hi @tfranchi  Unfortunately it looks like perhaps those fields are explicitly disallowed from being modified/set via API requests.  It's unclear to me if perhaps the API allowed it in the past (when this library was first created), but then later changed to be excluded, or if it was always disallowed.

I'd suggest reaching out to Pardot support and discussing with them the limitation, if there are any potential work arounds for your use case, or submit a feature request.

Sorry I can't be more help :/
