### ISSUE TITLE
Prospects Read Batch not implemented

### ISSUE THREAD

**Issue by epic-alex-rodionov** [Crim/pardot-java-client#81]
It would be good to have this implementation, because Pardot API calls are limited.
@Crim is it possible to implement by you or you need help with it?

We need to have similar like this if possible:
existing: `public Optional<Prospect> prospectRead(final ProspectReadRequest request) `
expecting: `public List<Prospect> prospectRead(List<ProspectReadRequest> request)`

**Comment by Crim** [comment]
Im out on mobile now so it's difficult for me to dog directly in at the moment.... but I believe there's a prospect query api end point and a way to use it?

https://developer.pardot.com/kb/api-version-4/prospects/#prospect-query

Does that support bulk reading prospects?  Or is there a different api endpoint you want to add support for?

**Comment by epic-alex-rodionov** [comment]
@Crim Looks like you are right: Pardot API does not support batch read at all: https://developer.pardot.com/kb/api-version-4/prospects/#prospect-read

**Comment by Crim** [comment]
I'm surprised that that prospect/query end point doesn't support a 'where prospectid in <list of IDs>' for bulk retrieving.  

As it stands you'd need to retrieve them by a common list, or iterate thru all prospects using 'where id is greater than <lastID retrieved> order by Id ascending'

**Comment by epic-alex-rodionov** [comment]
What do you mean? Can you please give an example?

**Comment by epic-alex-rodionov** [comment]
@Crim I think you mentioned about `ProspectQueryRequest`. I'll try to implement this approach..

**Comment by Crim** [comment]
https://developer.pardot.com/kb/bulk-data-pull/#example-of-paging-through-a-large-set-of-results

Probably explains the process better than I can
